// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace PutraJayaNT.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update5));
        
        string IMigrationMetadata.Id
        {
            get { return "201602150139258_Update5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
